name: flutter_malayalam_speech
description: Malayalam Speech Recognition with Google Speech-to-Text
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_speech: ^5.3.0
  permission_handler: ^11.0.1
  flutter_sound: ^9.3.7
  share_plus: ^8.0.2
  html_unescape: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
